name: flutter_avif_macos
description: Macos implementation for flutter_avif.
version: 1.1.0
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_macos

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  plugin:
    implements: flutter_avif
    platforms:
      macos:
        pluginClass: FlutterAvifPlugin
        dartPluginClass: FlutterAvifMacos
