name: flutter_avif_platform_interface
description: Common platform interface for the flutter_avif plugin.
version: 1.1.0
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_platform_interface

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: "1.72.0"
  meta: ^1.8.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^7.2.6