name: flutter_avif_platform_interface
description: Common platform interface for the flutter_avif plugin.
version: 2.4.1
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_platform_interface

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.1.0
  meta: ^1.9.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  ffigen: ^9.0.1