name: flutter_avif
description: A flutter plugin to view and encode avif images using libavif.
version: 2.1.1
repository: https://github.com/yekeskin/flutter_avif

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface: ^2.1.1
  flutter_avif_android: ^2.1.1
  flutter_avif_ios: ^2.1.1
  flutter_avif_macos: ^2.1.1
  flutter_avif_linux: ^2.1.1
  flutter_avif_windows: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_avif_android
      ios:
        default_package: flutter_avif_ios
      macos:
        default_package: flutter_avif_macos
      linux:
        default_package: flutter_avif_linux
      windows:
        default_package: flutter_avif_windows
