name: flutter_avif
description: Avif support for Flutter.
version: 0.0.1
repository: https://github.com/yekeskin/flutter_avif

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface:
    path: ../flutter_avif_platform_interface
  flutter_avif_android:
    path: ../flutter_avif_android
  flutter_avif_ios:
    path: ../flutter_avif_ios
  flutter_avif_macos:
    path: ../flutter_avif_macos
  flutter_avif_linux:
    path: ../flutter_avif_linux
  flutter_avif_windows:
    path: ../flutter_avif_windows
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_avif_android
      ios:
        default_package: flutter_avif_ios
      macos:
        default_package: flutter_avif_macos
      linux:
        default_package: flutter_avif_linux
      windows:
        default_package: flutter_avif_windows
