name: flutter_avif
description: A flutter plugin to view and encode avif images using libavif.
version: 3.0.0
repository: https://github.com/yekeskin/flutter_avif

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface: ^3.0.0
  flutter_avif_android: ^3.0.0
  flutter_avif_ios: ^3.0.0
  flutter_avif_macos: ^3.0.0
  flutter_avif_linux: ^3.0.0
  flutter_avif_windows: ^3.0.0
  flutter_avif_web: ^3.0.0
  http: ^1.2.2
  exif: ^3.3.0
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_avif_android
      ios:
        default_package: flutter_avif_ios
      macos:
        default_package: flutter_avif_macos
      linux:
        default_package: flutter_avif_linux
      windows:
        default_package: flutter_avif_windows
      web:
        default_package: flutter_avif_web
